# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [203]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [204]:
import tensorflow as tf
print(tf.__version__)

2.4.1

In [205]:
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
from sklearn import datasets

### Set random seed

In [206]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [207]:
iris = datasets.load_iris()
iris

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== ==== ======= ===== ====================\n\n    :Missing Attribute Values: None\n    :Class Distribution: 33.3% for each of 3 classes.\n    :Creator: R.A. Fisher\n    :Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n    :Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n.. topic:: References\n\n   - Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n     Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n     Mathematical Statistics" (John Wiley, NY, 1950).\n   - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n     (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n   - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n     Structure and Classification Rule for Recognition in Partially Exposed\n     Environments".  IEEE Transactions on Pattern Analysis and Machine\n     Intelligence, Vol. PAMI-2, No. 1, 67-71.\n   - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n     on Information Theory, May 1972, 431-433.\n   - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n     conceptual clustering system finds 3 classes in the data.\n   - Many, many more ...',
 'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5.5, 4.2, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.2],
        [5. , 3.2, 1.2, 0.2],
        [5.5, 3.5, 1.3, 0.2],
        [4.9, 3.6, 1.4, 0.1],
        [4.4, 3. , 1.3, 0.2],
        [5.1, 3.4, 1.5, 0.2],
        [5. , 3.5, 1.3, 0.3],
        [4.5, 2.3, 1.3, 0.3],
        [4.4, 3.2, 1.3, 0.2],
        [5. , 3.5, 1.6, 0.6],
        [5.1, 3.8, 1.9, 0.4],
        [4.8, 3. , 1.4, 0.3],
        [5.1, 3.8, 1.6, 0.2],
        [4.6, 3.2, 1.4, 0.2],
        [5.3, 3.7, 1.5, 0.2],
        [5. , 3.3, 1.4, 0.2],
        [7. , 3.2, 4.7, 1.4],
        [6.4, 3.2, 4.5, 1.5],
        [6.9, 3.1, 4.9, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [6.5, 2.8, 4.6, 1.5],
        [5.7, 2.8, 4.5, 1.3],
        [6.3, 3.3, 4.7, 1.6],
        [4.9, 2.4, 3.3, 1. ],
        [6.6, 2.9, 4.6, 1.3],
        [5.2, 2.7, 3.9, 1.4],
        [5. , 2. , 3.5, 1. ],
        [5.9, 3. , 4.2, 1.5],
        [6. , 2.2, 4. , 1. ],
        [6.1, 2.9, 4.7, 1.4],
        [5.6, 2.9, 3.6, 1.3],
        [6.7, 3.1, 4.4, 1.4],
        [5.6, 3. , 4.5, 1.5],
        [5.8, 2.7, 4.1, 1. ],
        [6.2, 2.2, 4.5, 1.5],
        [5.6, 2.5, 3.9, 1.1],
        [5.9, 3.2, 4.8, 1.8],
        [6.1, 2.8, 4. , 1.3],
        [6.3, 2.5, 4.9, 1.5],
        [6.1, 2.8, 4.7, 1.2],
        [6.4, 2.9, 4.3, 1.3],
        [6.6, 3. , 4.4, 1.4],
        [6.8, 2.8, 4.8, 1.4],
        [6.7, 3. , 5. , 1.7],
        [6. , 2.9, 4.5, 1.5],
        [5.7, 2.6, 3.5, 1. ],
        [5.5, 2.4, 3.8, 1.1],
        [5.5, 2.4, 3.7, 1. ],
        [5.8, 2.7, 3.9, 1.2],
        [6. , 2.7, 5.1, 1.6],
        [5.4, 3. , 4.5, 1.5],
        [6. , 3.4, 4.5, 1.6],
        [6.7, 3.1, 4.7, 1.5],
        [6.3, 2.3, 4.4, 1.3],
        [5.6, 3. , 4.1, 1.3],
        [5.5, 2.5, 4. , 1.3],
        [5.5, 2.6, 4.4, 1.2],
        [6.1, 3. , 4.6, 1.4],
        [5.8, 2.6, 4. , 1.2],
        [5. , 2.3, 3.3, 1. ],
        [5.6, 2.7, 4.2, 1.3],
        [5.7, 3. , 4.2, 1.2],
        [5.7, 2.9, 4.2, 1.3],
        [6.2, 2.9, 4.3, 1.3],
        [5.1, 2.5, 3. , 1.1],
        [5.7, 2.8, 4.1, 1.3],
        [6.3, 3.3, 6. , 2.5],
        [5.8, 2.7, 5.1, 1.9],
        [7.1, 3. , 5.9, 2.1],
        [6.3, 2.9, 5.6, 1.8],
        [6.5, 3. , 5.8, 2.2],
        [7.6, 3. , 6.6, 2.1],
        [4.9, 2.5, 4.5, 1.7],
        [7.3, 2.9, 6.3, 1.8],
        [6.7, 2.5, 5.8, 1.8],
        [7.2, 3.6, 6.1, 2.5],
        [6.5, 3.2, 5.1, 2. ],
        [6.4, 2.7, 5.3, 1.9],
        [6.8, 3. , 5.5, 2.1],
        [5.7, 2.5, 5. , 2. ],
        [5.8, 2.8, 5.1, 2.4],
        [6.4, 3.2, 5.3, 2.3],
        [6.5, 3. , 5.5, 1.8],
        [7.7, 3.8, 6.7, 2.2],
        [7.7, 2.6, 6.9, 2.3],
        [6. , 2.2, 5. , 1.5],
        [6.9, 3.2, 5.7, 2.3],
        [5.6, 2.8, 4.9, 2. ],
        [7.7, 2.8, 6.7, 2. ],
        [6.3, 2.7, 4.9, 1.8],
        [6.7, 3.3, 5.7, 2.1],
        [7.2, 3.2, 6. , 1.8],
        [6.2, 2.8, 4.8, 1.8],
        [6.1, 3. , 4.9, 1.8],
        [6.4, 2.8, 5.6, 2.1],
        [7.2, 3. , 5.8, 1.6],
        [7.4, 2.8, 6.1, 1.9],
        [7.9, 3.8, 6.4, 2. ],
        [6.4, 2.8, 5.6, 2.2],
        [6.3, 2.8, 5.1, 1.5],
        [6.1, 2.6, 5.6, 1.4],
        [7.7, 3. , 6.1, 2.3],
        [6.3, 3.4, 5.6, 2.4],
        [6.4, 3.1, 5.5, 1.8],
        [6. , 3. , 4.8, 1.8],
        [6.9, 3.1, 5.4, 2.1],
        [6.7, 3.1, 5.6, 2.4],
        [6.9, 3.1, 5.1, 2.3],
        [5.8, 2.7, 5.1, 1.9],
        [6.8, 3.2, 5.9, 2.3],
        [6.7, 3.3, 5.7, 2.5],
        [6.7, 3. , 5.2, 2.3],
        [6.3, 2.5, 5. , 1.9],
        [6.5, 3. , 5.2, 2. ],
        [6.2, 3.4, 5.4, 2.3],
        [5.9, 3. , 5.1, 1.8]]),
 'feature_names': ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 'filename': '/usr/local/lib/python3.7/dist-packages/sklearn/datasets/data/iris.csv',
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 'target_names': array(['setosa', 'versicolor', 'virginica'], dtype='<U10')}

In [208]:
type(iris)

sklearn.utils.Bunch

In [209]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [210]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [211]:
X=iris.data
y=iris.target

In [212]:
print("Shape of iris dataset X and y are:", X.shape, y.shape)

Shape of iris dataset X and y are: (150, 4) (150,)

In [213]:
print(X[0,:])
print(np.unique(y))

[5.1 3.5 1.4 0.2]
[0 1 2]

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [214]:
#split train and test data into 70:30 ratio
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=15)

In [215]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((112, 4), (112,), (38, 4), (38,))

In [216]:
print(np.unique(y_train))
print(np.unique(y_test))

[0 1 2]
[0 1 2]

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [217]:
#One hot encoding
y_train = tf.keras.utils.to_categorical(y_train, num_classes=3)
y_test = tf.keras.utils.to_categorical(y_test, num_classes=3)

In [218]:
print(y_train)
print(y_test)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]

## Question 5

### Initialize a sequential model
- Define a sequential model

In [219]:
#Initialize Sequential model
model = tf.keras.models.Sequential()

#another way of defining a sequential
#model = tf.keras.Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [220]:
#Add Dense layer for prediction - Keras declares weights and bias automatically
model.add(tf.keras.layers.Dense(3, input_shape=(4,), activation='softmax'))
#4 inputs + 1 bias  w=1 and b=1. so applying in y=wx+b ==> y=1x4+1 =5. Since there are 3 output in target, it would be 5*3=15 params.

In [221]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_7 (Dense)              (None, 3)                 15
=================================================================
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [222]:
#Compile the model - add Loss and Gradient Descent optimizer
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [223]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_7 (Dense)              (None, 3)                 15
=================================================================
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________

## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [224]:
model.fit(X_train, y_train,
          validation_data=(X_test, y_test), 
          epochs=100,
          #batch_size=32)
          batch_size=X_train.shape[0])

Epoch 1/100
1/1 [==============================] - 0s 477ms/step - loss: 3.1866 - accuracy: 0.3393 - val_loss: 2.7569 - val_accuracy: 0.3158
Epoch 2/100
1/1 [==============================] - 0s 42ms/step - loss: 2.7595 - accuracy: 0.3393 - val_loss: 2.3638 - val_accuracy: 0.3158
Epoch 3/100
1/1 [==============================] - 0s 44ms/step - loss: 2.3795 - accuracy: 0.3393 - val_loss: 2.0362 - val_accuracy: 0.3158
Epoch 4/100
1/1 [==============================] - 0s 39ms/step - loss: 2.0646 - accuracy: 0.3393 - val_loss: 1.7848 - val_accuracy: 0.3158
Epoch 5/100
1/1 [==============================] - 0s 42ms/step - loss: 1.8244 - accuracy: 0.3393 - val_loss: 1.6049 - val_accuracy: 0.3158
Epoch 6/100
1/1 [==============================] - 0s 42ms/step - loss: 1.6532 - accuracy: 0.3393 - val_loss: 1.4800 - val_accuracy: 0.3158
Epoch 7/100
1/1 [==============================] - 0s 46ms/step - loss: 1.5340 - accuracy: 0.3125 - val_loss: 1.3926 - val_accuracy: 0.3158
Epoch 8/100
1/1 [==============================] - 0s 50ms/step - loss: 1.4498 - accuracy: 0.2768 - val_loss: 1.3300 - val_accuracy: 0.2105
Epoch 9/100
1/1 [==============================] - 0s 48ms/step - loss: 1.3884 - accuracy: 0.1786 - val_loss: 1.2839 - val_accuracy: 0.1842
Epoch 10/100
1/1 [==============================] - 0s 43ms/step - loss: 1.3422 - accuracy: 0.1161 - val_loss: 1.2491 - val_accuracy: 0.1842
Epoch 11/100
1/1 [==============================] - 0s 49ms/step - loss: 1.3063 - accuracy: 0.1161 - val_loss: 1.2222 - val_accuracy: 0.1316
Epoch 12/100
1/1 [==============================] - 0s 42ms/step - loss: 1.2779 - accuracy: 0.1339 - val_loss: 1.2011 - val_accuracy: 0.1053
Epoch 13/100
1/1 [==============================] - 0s 45ms/step - loss: 1.2548 - accuracy: 0.1696 - val_loss: 1.1840 - val_accuracy: 0.1053
Epoch 14/100
1/1 [==============================] - 0s 43ms/step - loss: 1.2357 - accuracy: 0.1875 - val_loss: 1.1697 - val_accuracy: 0.1579
Epoch 15/100
1/1 [==============================] - 0s 41ms/step - loss: 1.2194 - accuracy: 0.1875 - val_loss: 1.1575 - val_accuracy: 0.1579
Epoch 16/100
1/1 [==============================] - 0s 42ms/step - loss: 1.2051 - accuracy: 0.1875 - val_loss: 1.1467 - val_accuracy: 0.1842
Epoch 17/100
1/1 [==============================] - 0s 45ms/step - loss: 1.1923 - accuracy: 0.2232 - val_loss: 1.1368 - val_accuracy: 0.2105
Epoch 18/100
1/1 [==============================] - 0s 41ms/step - loss: 1.1806 - accuracy: 0.2143 - val_loss: 1.1277 - val_accuracy: 0.2368
Epoch 19/100
1/1 [==============================] - 0s 47ms/step - loss: 1.1696 - accuracy: 0.2054 - val_loss: 1.1190 - val_accuracy: 0.2632
Epoch 20/100
1/1 [==============================] - 0s 43ms/step - loss: 1.1592 - accuracy: 0.2232 - val_loss: 1.1106 - val_accuracy: 0.2632
Epoch 21/100
1/1 [==============================] - 0s 43ms/step - loss: 1.1493 - accuracy: 0.2411 - val_loss: 1.1025 - val_accuracy: 0.2895
Epoch 22/100
1/1 [==============================] - 0s 44ms/step - loss: 1.1397 - accuracy: 0.2411 - val_loss: 1.0946 - val_accuracy: 0.2632
Epoch 23/100
1/1 [==============================] - 0s 42ms/step - loss: 1.1304 - accuracy: 0.2411 - val_loss: 1.0869 - val_accuracy: 0.1842
Epoch 24/100
1/1 [==============================] - 0s 39ms/step - loss: 1.1213 - accuracy: 0.2411 - val_loss: 1.0793 - val_accuracy: 0.2105
Epoch 25/100
1/1 [==============================] - 0s 64ms/step - loss: 1.1124 - accuracy: 0.2411 - val_loss: 1.0718 - val_accuracy: 0.2105
Epoch 26/100
1/1 [==============================] - 0s 42ms/step - loss: 1.1037 - accuracy: 0.2500 - val_loss: 1.0644 - val_accuracy: 0.2105
Epoch 27/100
1/1 [==============================] - 0s 47ms/step - loss: 1.0951 - accuracy: 0.2500 - val_loss: 1.0572 - val_accuracy: 0.2105
Epoch 28/100
1/1 [==============================] - 0s 43ms/step - loss: 1.0867 - accuracy: 0.2500 - val_loss: 1.0500 - val_accuracy: 0.2105
Epoch 29/100
1/1 [==============================] - 0s 49ms/step - loss: 1.0784 - accuracy: 0.2589 - val_loss: 1.0430 - val_accuracy: 0.2368
Epoch 30/100
1/1 [==============================] - 0s 44ms/step - loss: 1.0703 - accuracy: 0.2500 - val_loss: 1.0360 - val_accuracy: 0.2368
Epoch 31/100
1/1 [==============================] - 0s 45ms/step - loss: 1.0623 - accuracy: 0.2500 - val_loss: 1.0292 - val_accuracy: 0.2368
Epoch 32/100
1/1 [==============================] - 0s 48ms/step - loss: 1.0544 - accuracy: 0.2500 - val_loss: 1.0225 - val_accuracy: 0.2368
Epoch 33/100
1/1 [==============================] - 0s 49ms/step - loss: 1.0467 - accuracy: 0.2500 - val_loss: 1.0159 - val_accuracy: 0.2368
Epoch 34/100
1/1 [==============================] - 0s 56ms/step - loss: 1.0391 - accuracy: 0.2500 - val_loss: 1.0094 - val_accuracy: 0.2368
Epoch 35/100
1/1 [==============================] - 0s 51ms/step - loss: 1.0316 - accuracy: 0.2589 - val_loss: 1.0029 - val_accuracy: 0.2632
Epoch 36/100
1/1 [==============================] - 0s 49ms/step - loss: 1.0243 - accuracy: 0.2589 - val_loss: 0.9966 - val_accuracy: 0.2895
Epoch 37/100
1/1 [==============================] - 0s 42ms/step - loss: 1.0170 - accuracy: 0.2589 - val_loss: 0.9904 - val_accuracy: 0.3158
Epoch 38/100
1/1 [==============================] - 0s 42ms/step - loss: 1.0099 - accuracy: 0.2679 - val_loss: 0.9843 - val_accuracy: 0.3158
Epoch 39/100
1/1 [==============================] - 0s 41ms/step - loss: 1.0029 - accuracy: 0.2768 - val_loss: 0.9783 - val_accuracy: 0.3421
Epoch 40/100
1/1 [==============================] - 0s 45ms/step - loss: 0.9960 - accuracy: 0.2857 - val_loss: 0.9723 - val_accuracy: 0.3684
Epoch 41/100
1/1 [==============================] - 0s 38ms/step - loss: 0.9893 - accuracy: 0.2857 - val_loss: 0.9665 - val_accuracy: 0.3947
Epoch 42/100
1/1 [==============================] - 0s 44ms/step - loss: 0.9826 - accuracy: 0.3125 - val_loss: 0.9608 - val_accuracy: 0.3947
Epoch 43/100
1/1 [==============================] - 0s 45ms/step - loss: 0.9761 - accuracy: 0.3125 - val_loss: 0.9551 - val_accuracy: 0.3947
Epoch 44/100
1/1 [==============================] - 0s 47ms/step - loss: 0.9696 - accuracy: 0.3125 - val_loss: 0.9496 - val_accuracy: 0.3947
Epoch 45/100
1/1 [==============================] - 0s 45ms/step - loss: 0.9633 - accuracy: 0.3304 - val_loss: 0.9441 - val_accuracy: 0.4211
Epoch 46/100
1/1 [==============================] - 0s 45ms/step - loss: 0.9571 - accuracy: 0.3929 - val_loss: 0.9387 - val_accuracy: 0.4211
Epoch 47/100
1/1 [==============================] - 0s 41ms/step - loss: 0.9510 - accuracy: 0.4286 - val_loss: 0.9334 - val_accuracy: 0.4211
Epoch 48/100
1/1 [==============================] - 0s 40ms/step - loss: 0.9449 - accuracy: 0.4464 - val_loss: 0.9282 - val_accuracy: 0.5000
Epoch 49/100
1/1 [==============================] - 0s 42ms/step - loss: 0.9390 - accuracy: 0.4643 - val_loss: 0.9231 - val_accuracy: 0.5000
Epoch 50/100
1/1 [==============================] - 0s 44ms/step - loss: 0.9332 - accuracy: 0.5000 - val_loss: 0.9180 - val_accuracy: 0.5000
Epoch 51/100
1/1 [==============================] - 0s 53ms/step - loss: 0.9275 - accuracy: 0.5089 - val_loss: 0.9130 - val_accuracy: 0.5000
Epoch 52/100
1/1 [==============================] - 0s 47ms/step - loss: 0.9218 - accuracy: 0.5179 - val_loss: 0.9081 - val_accuracy: 0.5263
Epoch 53/100
1/1 [==============================] - 0s 53ms/step - loss: 0.9163 - accuracy: 0.5179 - val_loss: 0.9033 - val_accuracy: 0.5263
Epoch 54/100
1/1 [==============================] - 0s 46ms/step - loss: 0.9108 - accuracy: 0.5179 - val_loss: 0.8986 - val_accuracy: 0.5526
Epoch 55/100
1/1 [==============================] - 0s 38ms/step - loss: 0.9054 - accuracy: 0.5357 - val_loss: 0.8939 - val_accuracy: 0.5526
Epoch 56/100
1/1 [==============================] - 0s 48ms/step - loss: 0.9002 - accuracy: 0.5357 - val_loss: 0.8893 - val_accuracy: 0.5526
Epoch 57/100
1/1 [==============================] - 0s 46ms/step - loss: 0.8950 - accuracy: 0.5446 - val_loss: 0.8848 - val_accuracy: 0.5526
Epoch 58/100
1/1 [==============================] - 0s 49ms/step - loss: 0.8899 - accuracy: 0.5446 - val_loss: 0.8803 - val_accuracy: 0.5526
Epoch 59/100
1/1 [==============================] - 0s 55ms/step - loss: 0.8848 - accuracy: 0.5625 - val_loss: 0.8759 - val_accuracy: 0.5789
Epoch 60/100
1/1 [==============================] - 0s 47ms/step - loss: 0.8799 - accuracy: 0.5714 - val_loss: 0.8716 - val_accuracy: 0.5789
Epoch 61/100
1/1 [==============================] - 0s 44ms/step - loss: 0.8750 - accuracy: 0.5714 - val_loss: 0.8673 - val_accuracy: 0.6053
Epoch 62/100
1/1 [==============================] - 0s 42ms/step - loss: 0.8702 - accuracy: 0.5714 - val_loss: 0.8631 - val_accuracy: 0.6053
Epoch 63/100
1/1 [==============================] - 0s 51ms/step - loss: 0.8655 - accuracy: 0.5714 - val_loss: 0.8590 - val_accuracy: 0.6053
Epoch 64/100
1/1 [==============================] - 0s 53ms/step - loss: 0.8609 - accuracy: 0.5893 - val_loss: 0.8549 - val_accuracy: 0.6053
Epoch 65/100
1/1 [==============================] - 0s 54ms/step - loss: 0.8563 - accuracy: 0.6071 - val_loss: 0.8509 - val_accuracy: 0.6316
Epoch 66/100
1/1 [==============================] - 0s 49ms/step - loss: 0.8518 - accuracy: 0.6071 - val_loss: 0.8470 - val_accuracy: 0.6316
Epoch 67/100
1/1 [==============================] - 0s 44ms/step - loss: 0.8474 - accuracy: 0.6071 - val_loss: 0.8431 - val_accuracy: 0.6316
Epoch 68/100
1/1 [==============================] - 0s 44ms/step - loss: 0.8430 - accuracy: 0.6071 - val_loss: 0.8392 - val_accuracy: 0.6316
Epoch 69/100
1/1 [==============================] - 0s 50ms/step - loss: 0.8387 - accuracy: 0.6071 - val_loss: 0.8355 - val_accuracy: 0.6316
Epoch 70/100
1/1 [==============================] - 0s 42ms/step - loss: 0.8345 - accuracy: 0.6071 - val_loss: 0.8317 - val_accuracy: 0.6316
Epoch 71/100
1/1 [==============================] - 0s 44ms/step - loss: 0.8303 - accuracy: 0.6071 - val_loss: 0.8281 - val_accuracy: 0.6316
Epoch 72/100
1/1 [==============================] - 0s 51ms/step - loss: 0.8262 - accuracy: 0.6071 - val_loss: 0.8244 - val_accuracy: 0.6316
Epoch 73/100
1/1 [==============================] - 0s 54ms/step - loss: 0.8222 - accuracy: 0.6071 - val_loss: 0.8209 - val_accuracy: 0.6316
Epoch 74/100
1/1 [==============================] - 0s 51ms/step - loss: 0.8182 - accuracy: 0.6071 - val_loss: 0.8174 - val_accuracy: 0.6316
Epoch 75/100
1/1 [==============================] - 0s 50ms/step - loss: 0.8143 - accuracy: 0.6071 - val_loss: 0.8139 - val_accuracy: 0.6316
Epoch 76/100
1/1 [==============================] - 0s 48ms/step - loss: 0.8105 - accuracy: 0.6250 - val_loss: 0.8105 - val_accuracy: 0.6316
Epoch 77/100
1/1 [==============================] - 0s 49ms/step - loss: 0.8067 - accuracy: 0.6339 - val_loss: 0.8071 - val_accuracy: 0.6316
Epoch 78/100
1/1 [==============================] - 0s 49ms/step - loss: 0.8029 - accuracy: 0.6339 - val_loss: 0.8038 - val_accuracy: 0.6316
Epoch 79/100
1/1 [==============================] - 0s 42ms/step - loss: 0.7992 - accuracy: 0.6429 - val_loss: 0.8005 - val_accuracy: 0.6316
Epoch 80/100
1/1 [==============================] - 0s 47ms/step - loss: 0.7956 - accuracy: 0.6518 - val_loss: 0.7973 - val_accuracy: 0.6316
Epoch 81/100
1/1 [==============================] - 0s 47ms/step - loss: 0.7920 - accuracy: 0.6518 - val_loss: 0.7941 - val_accuracy: 0.6316
Epoch 82/100
1/1 [==============================] - 0s 51ms/step - loss: 0.7885 - accuracy: 0.6607 - val_loss: 0.7910 - val_accuracy: 0.6316
Epoch 83/100
1/1 [==============================] - 0s 43ms/step - loss: 0.7851 - accuracy: 0.6607 - val_loss: 0.7879 - val_accuracy: 0.6316
Epoch 84/100
1/1 [==============================] - 0s 39ms/step - loss: 0.7816 - accuracy: 0.6696 - val_loss: 0.7848 - val_accuracy: 0.6316
Epoch 85/100
1/1 [==============================] - 0s 45ms/step - loss: 0.7783 - accuracy: 0.6696 - val_loss: 0.7818 - val_accuracy: 0.6316
Epoch 86/100
1/1 [==============================] - 0s 51ms/step - loss: 0.7749 - accuracy: 0.6696 - val_loss: 0.7789 - val_accuracy: 0.6316
Epoch 87/100
1/1 [==============================] - 0s 48ms/step - loss: 0.7717 - accuracy: 0.6786 - val_loss: 0.7759 - val_accuracy: 0.6316
Epoch 88/100
1/1 [==============================] - 0s 45ms/step - loss: 0.7684 - accuracy: 0.6786 - val_loss: 0.7730 - val_accuracy: 0.6316
Epoch 89/100
1/1 [==============================] - 0s 49ms/step - loss: 0.7652 - accuracy: 0.6786 - val_loss: 0.7702 - val_accuracy: 0.6316
Epoch 90/100
1/1 [==============================] - 0s 53ms/step - loss: 0.7621 - accuracy: 0.6875 - val_loss: 0.7674 - val_accuracy: 0.6316
Epoch 91/100
1/1 [==============================] - 0s 52ms/step - loss: 0.7590 - accuracy: 0.6875 - val_loss: 0.7646 - val_accuracy: 0.6316
Epoch 92/100
1/1 [==============================] - 0s 42ms/step - loss: 0.7560 - accuracy: 0.6875 - val_loss: 0.7619 - val_accuracy: 0.6316
Epoch 93/100
1/1 [==============================] - 0s 45ms/step - loss: 0.7530 - accuracy: 0.6875 - val_loss: 0.7592 - val_accuracy: 0.6316
Epoch 94/100
1/1 [==============================] - 0s 47ms/step - loss: 0.7500 - accuracy: 0.6964 - val_loss: 0.7565 - val_accuracy: 0.6316
Epoch 95/100
1/1 [==============================] - 0s 47ms/step - loss: 0.7471 - accuracy: 0.6964 - val_loss: 0.7538 - val_accuracy: 0.6316
Epoch 96/100
1/1 [==============================] - 0s 49ms/step - loss: 0.7442 - accuracy: 0.6964 - val_loss: 0.7512 - val_accuracy: 0.6316
Epoch 97/100
1/1 [==============================] - 0s 55ms/step - loss: 0.7413 - accuracy: 0.6964 - val_loss: 0.7487 - val_accuracy: 0.6316
Epoch 98/100
1/1 [==============================] - 0s 47ms/step - loss: 0.7385 - accuracy: 0.6964 - val_loss: 0.7461 - val_accuracy: 0.6316
Epoch 99/100
1/1 [==============================] - 0s 51ms/step - loss: 0.7357 - accuracy: 0.6964 - val_loss: 0.7436 - val_accuracy: 0.6316
Epoch 100/100
1/1 [==============================] - 0s 43ms/step - loss: 0.7330 - accuracy: 0.6964 - val_loss: 0.7412 - val_accuracy: 0.6316

## Question 10

### Make predictions
- Predict labels on one row

In [225]:
input_data = np.expand_dims(X_test[0], axis=0)
input_data.shape

(1, 4)

In [226]:
pred = model.predict(input_data)

In [227]:
pred[0]

array([0.60213184, 0.06256179, 0.33530638], dtype=float32)

In [228]:
pred.shape

(1, 3)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [229]:
y_test[0]

array([1., 0., 0.], dtype=float32)

By comparing the actual label with the prediction, the class 0 has highest % value of 87% and the model predicted correctly as 1 - which is class 0.



---

# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [230]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [231]:
import tensorflow as tf
print(tf.__version__)

2.4.1

### Set random seed

In [232]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [254]:
# run this cell to upload file if you are using google colab
from google.colab import files
files.upload()

In [234]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [235]:
df_prices=pd.read_csv('prices.csv',error_bad_lines=False, encoding="latin-1")

In [236]:
df_prices.head()

                  date symbol        open  ...         low        high     volume
0  2016-01-05 00:00:00   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1  2016-01-06 00:00:00   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2  2016-01-07 00:00:00   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3  2016-01-08 00:00:00   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4  2016-01-11 00:00:00   WLTW  117.010002  ...  114.089996  117.330002  1408600.0

[5 rows x 7 columns]

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [237]:
df_prices.drop(['date','symbol'], axis=1, inplace=True)

In [238]:
df_prices.head()

         open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

In [239]:
print("shape of price dataset:", df_prices.shape)

shape of price dataset: (851264, 5)

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [240]:
df_prices_final=df_prices.iloc[:1000]

#another easy way--
#df_prices_final=df_prices.head(1000)

In [241]:
df_prices_final.shape

(1000, 5)

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [242]:
X=df_prices_final.iloc[:,0:4]
Y=df_prices_final.iloc[:, 4:5]/1000000

In [243]:
X.head()

         open       close         low        high
0  123.430000  125.839996  122.309998  126.250000
1  125.239998  119.980003  119.940002  125.540001
2  116.379997  114.949997  114.930000  119.739998
3  115.480003  116.620003  113.500000  117.440002
4  117.010002  114.970001  114.089996  117.330002

In [244]:
Y.head()

   volume
0  2.1636
1  2.3864
2  2.4895
3  2.0063
4  1.4086

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [245]:
X=np.asarray(X, dtype='float32')
Y=np.asarray(Y, dtype='float32')

#Another method
#X=np.array(X).astype('float32')
#Y=np.array(Y).astype('float32')

In [ ]:
type(X), type(Y)

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [246]:
X=tf.math.l2_normalize(X)

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [247]:
#We are initializing weights and Bias with Zero
w = tf.zeros(shape=(4,1))
b = tf.zeros(shape=(1))

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [248]:
@tf.function
def prediction(x, w, b):
    
    xw_matmul = tf.matmul(x, w)
    yb = tf.add(xw_matmul, b)
    
    return yb

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [249]:
@tf.function
def loss(y_actual, y_predicted):   #rmse = (y-ybar)^2/n
    
    diff = y_actual - y_predicted
    sqr = tf.square(diff)
    avg = tf.reduce_mean(sqr)
    
    return avg

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [250]:
@tf.function
def train(X, y_actual, w, b, learning_rate=0.01):
    
    #Record mathematical operations on 'tape' to calculate loss
    with tf.GradientTape() as t:
        
        t.watch([w,b])
        
        current_prediction = prediction(X, w, b)
        current_loss = loss(y_actual, current_prediction)
    
    #Calculate Gradients for Loss with respect to Weights and Bias
    dw, db = t.gradient(current_loss,[w, b])
    
    #Update Weights and Bias
    w = w - learning_rate*dw
    b = b - learning_rate*db
    
    return w, b

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [251]:
#Train for 100 Steps
for i in range(100):
    
    w, b = train(X, Y, w, b, learning_rate=0.01)
    print('Current Loss on iteration', i, loss(Y, prediction(X, w, b)).numpy())

Current Loss on iteration 0 236.16805
Current Loss on iteration 1 235.09369
Current Loss on iteration 2 234.06194
Current Loss on iteration 3 233.07103
Current Loss on iteration 4 232.11937
Current Loss on iteration 5 231.20546
Current Loss on iteration 6 230.32774
Current Loss on iteration 7 229.4848
Current Loss on iteration 8 228.67522
Current Loss on iteration 9 227.89775
Current Loss on iteration 10 227.15106
Current Loss on iteration 11 226.43399
Current Loss on iteration 12 225.7453
Current Loss on iteration 13 225.08392
Current Loss on iteration 14 224.44872
Current Loss on iteration 15 223.83868
Current Loss on iteration 16 223.25284
Current Loss on iteration 17 222.69019
Current Loss on iteration 18 222.14981
Current Loss on iteration 19 221.6309
Current Loss on iteration 20 221.1325
Current Loss on iteration 21 220.65384
Current Loss on iteration 22 220.19417
Current Loss on iteration 23 219.75272
Current Loss on iteration 24 219.32877
Current Loss on iteration 25 218.92157
Current Loss on iteration 26 218.53053
Current Loss on iteration 27 218.15497
Current Loss on iteration 28 217.79427
Current Loss on iteration 29 217.44788
Current Loss on iteration 30 217.11522
Current Loss on iteration 31 216.79572
Current Loss on iteration 32 216.4889
Current Loss on iteration 33 216.19423
Current Loss on iteration 34 215.91125
Current Loss on iteration 35 215.63942
Current Loss on iteration 36 215.37843
Current Loss on iteration 37 215.1277
Current Loss on iteration 38 214.88698
Current Loss on iteration 39 214.65575
Current Loss on iteration 40 214.43372
Current Loss on iteration 41 214.22044
Current Loss on iteration 42 214.01562
Current Loss on iteration 43 213.81894
Current Loss on iteration 44 213.63004
Current Loss on iteration 45 213.4486
Current Loss on iteration 46 213.27434
Current Loss on iteration 47 213.107
Current Loss on iteration 48 212.94633
Current Loss on iteration 49 212.79196
Current Loss on iteration 50 212.64375
Current Loss on iteration 51 212.50139
Current Loss on iteration 52 212.36465
Current Loss on iteration 53 212.23337
Current Loss on iteration 54 212.10725
Current Loss on iteration 55 211.98619
Current Loss on iteration 56 211.86983
Current Loss on iteration 57 211.75816
Current Loss on iteration 58 211.65085
Current Loss on iteration 59 211.54784
Current Loss on iteration 60 211.44887
Current Loss on iteration 61 211.35385
Current Loss on iteration 62 211.26256
Current Loss on iteration 63 211.17491
Current Loss on iteration 64 211.09071
Current Loss on iteration 65 211.00986
Current Loss on iteration 66 210.93224
Current Loss on iteration 67 210.85765
Current Loss on iteration 68 210.78603
Current Loss on iteration 69 210.71725
Current Loss on iteration 70 210.65118
Current Loss on iteration 71 210.58775
Current Loss on iteration 72 210.52681
Current Loss on iteration 73 210.46828
Current Loss on iteration 74 210.4121
Current Loss on iteration 75 210.3581
Current Loss on iteration 76 210.30624
Current Loss on iteration 77 210.25647
Current Loss on iteration 78 210.20862
Current Loss on iteration 79 210.16272
Current Loss on iteration 80 210.11859
Current Loss on iteration 81 210.07622
Current Loss on iteration 82 210.03557
Current Loss on iteration 83 209.99648
Current Loss on iteration 84 209.95894
Current Loss on iteration 85 209.92293
Current Loss on iteration 86 209.88828
Current Loss on iteration 87 209.85503
Current Loss on iteration 88 209.82309
Current Loss on iteration 89 209.79243
Current Loss on iteration 90 209.76297
Current Loss on iteration 91 209.73466
Current Loss on iteration 92 209.70752
Current Loss on iteration 93 209.6814
Current Loss on iteration 94 209.65634
Current Loss on iteration 95 209.63226
Current Loss on iteration 96 209.60916
Current Loss on iteration 97 209.5869
Current Loss on iteration 98 209.5656
Current Loss on iteration 99 209.54509

### Observe values of Weight
- Print the updated values

In [252]:
#Check Weights and Bias
print('Weights:\n', w.numpy())

Weights:
 [[0.0194333 ]
 [0.01969694]
 [0.01937149]
 [0.01976266]]

### Observe values of Bias
- Print the updated values

In [253]:
print('Bias:\n',b.numpy())

Bias:
 [4.608607]