# Python basics
In this lab we will be covering up following things
- list
- dictionary
- function
- numpy
- pandas

# Question 1

## List
Sequences in python are data structures that hold objects in an ordered array. Now, we will work on list, the most common sequence data type in python.

This is how you define a list in Python
- Here we are defining a list named "list_1" using square braces "[ ]"

In [164]:
list_1 = ['learning', 'python', 'is fun!']

There is another way to define a list in Python
- Here we are defining a list named "list_2" using list() method

In [165]:
list_2 = list(('learning', 'for', 'life'))

### Append an element in a list
- Append number 10 to "list_1" given above
- Use append() method

In [166]:
#add number 10 to list_1
list_1.append(10)
print("Append number 10 to list_1:", list_1)

Append number 10 to list_1: ['learning', 'python', 'is fun!', 10]

### Remove an element from a list
- Do this after completing the previous step
- Remove number 10 from "list_1"
- Use remove() method

In [167]:
#remove number 10 from list_1
list_1.remove(10)
print("Remove number 10 from list_1:", list_1)

Remove number 10 from list_1: ['learning', 'python', 'is fun!']

### Join two lists
- Join list_1 and list_2
- Extend list_1 using list_2
- Use extend() method
- you can also use "+" operator to add two lists

In [28]:
#join two list or extend 2 list using + operator
list_1 + list_2
print(list_1 + list_2)

['learning', 'python', 'is fun!', 'learning', 'for', 'life']

In [29]:
print(list_1)

['learning', 'python', 'is fun!']

In [30]:
print(list_2)

['learning', 'for', 'life']

In [31]:
#extend list_1 using extend keyword
list_1.extend(list_2)
print(list_1)

['learning', 'python', 'is fun!', 'learning', 'for', 'life']

### Question 4
Number List

Find Range and Mean of l3.

`l3 = [2,4,6,8]`

Hint: use **`len()`, `sum()`, `min()`, `max()`** functions
 
If you want to use standard functions like mean & range, you have to import them from numpy else you can calculate them the traditional way using formulas

In [57]:
#calculate range using min() and max()
l3 = [2,4,6,8]
# print list values
print(l3)

#print length of list 
print(len(l3))

#print range using max of len - min of len
print("Range of l3 list using basic fn:", max(l3) - min(l3))

#print mean - total value of list / total # of element in the list
print("Mean of l3 list using basic fn:", sum(l3)/len(l3))

[2, 4, 6, 8]
4
Range of l3 list using basic fn: 6
Mean of l3 list using basic fn: 5.0

In [55]:
# calculate mean using numpy
import numpy as np

print("Mean of l3 list using numpy:", np.mean(l3))


print("Range of l3 list using numpy:", np.max(l3) - np.min(l3))

Mean of l3 list using numpy: 5.0
Range of l3 list using numpy: 6

### Sum up all the elements in a list
- Sum all the elements in "list_3"
- Use sum() method

# Question 3

### Calculate mean of values in a list
- Calculate mean of "list_3"
- Mean = sum of all elements in the list / number of elements in the list

In [59]:
#print mean - total value of list / total # of element in the list
print("Mean of list3:", sum(l3)/len(l3))

Mean of list3: 5.0

### Count the occurence of an element in a given list
- There is list given below named "list_4"
- Count the occurence of number 5 in "list_4"
- Use count() method

In [62]:
list_4 = [1, 2, 3, 5, 7, 5, 8, 9, 5, 3, 0, 7, 5]

In [64]:
#count the occurence of number 5 in a list

print("Occurrence of number 5 in a list_4:",list_4.count(5))

Occurrence of number 5 in a list_4: 4

# Question 4

## Function
- Below is a simple code to define function in python
- Below function named "sample_function" takes two arguments "a" and "b" and returns their product

In [0]:
def sample_function(a, b):
  product = a * b
  return product

- This is how you call a function in python

In [0]:
sample_function(2, 3)

6

### Define and call a function
- Define a function named "sum_three"
- It should take 3 numbers as arguments
- It should return the sum of 3 numbers
- Call the defined function giving required parameters

In [65]:
#define a function sum_three with 3 args - a, b, c.
def sum_three(a,b,c):
    sum3 = a+b+c
    return sum3

In [69]:
#call the defined function sum_three and print the value
sum_three(5,4,1)

10

## Lambda function
Anonymous function or no name function, which can be considered when you use a function only once

Below is an example of how you can define a lambda function

In [71]:
f = lambda x, y: x + y

Here's how you can call a lambda function using required parameters

### Define a lambda function
- Define a lambda function named "lambda_sum_three" which takes 3 arguments and sums them up
- Call the created function with required parameters

In [75]:
#Define a lambda function
lambda_sum_three = lambda a, b, c: a+b+c

In [77]:
#call lambda funtion with passing value to arguments.
sum3(2,3,4)

9

In [79]:
#another way of defining and passing values to the function

lambda_sum_three = (lambda a, b, c : a+b+c) (2,3,4)
print(lambda_sum_three)

9

# Question 5

## Numpy

Numpy adds support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

Let's import numpy

In [80]:
import numpy as np

Here's how you can create an array using numpy

In [81]:
np.array([1, 2, 3])

array([1, 2, 3])

### Create an identity array
- Create an identity 2d-array of order 3x3
- The identity array is a square array with ones on the main diagonal
- Use identity() method

In [93]:
#create identity array
import numpy as np
a = np.identity(3, dtype=int)
print("Identity Array of order 3x3:\n", a)


#Another way of creating identity using eye
a= np.eye(3)
print("Identity Array using eye method of order 3x3:", a)

Identity Array of order 3x3:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
Identity Array using eye method of order 3x3: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

### Create a 2d array
- Create a 2d-array of order 3x3 named "sample_array"
- First row: 1, 2, 3
- Second row: 4, 5, 6
- Third row: 7, 8, 9
- Arranged in the same order as above
- Use array() method

In [95]:
sample_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sample_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Question 6

### Add a number in all the elements of an array
- Add 1 to all the elements in the array "sample_array"
- "+" operator can be used to add a number to all elements in an array
- Similarly, you can do operations like scalar substraction, division, multiplication (operating on each element in the array)

In [99]:
#Add value 1 to each element in the sample_array


sample_array = sample_array +1

print("Sample Array after add value 1:",sample_array)

Sample Array after add value 1: [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

In [100]:
#Subtract value 1 from each element in the sample array
print("Sample Array after subtract value 1:",sample_array -1)

Sample Array after subtract value 1: [[1 2 3]
 [4 5 6]
 [7 8 9]]

In [101]:
#Divide operation

print("Sample Array after add value 1:",sample_array /1)

Sample Array after add value 1: [[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]

In [102]:
#Multiple operation

print("Sample Array after add value 1:",sample_array * 1)

Sample Array after add value 1: [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

### Find mean of all elements in an array
- Find mean of all elements in the array "sample_array"
- Use mean() method

In [105]:
#Mean of all elements

print("Mean of sample_array: ",sample_array.mean())

Mean of sample_array:  6.0

### Calculate dot product of two arrays
- We are giving you two arrays "a" and "b"
- Find the dot product of a and b
- Use dot() method

In [106]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [110]:
print("Dot product of array a and b: \n", np.dot(a,b))

Dot product of array a and b:
 [[19 22]
 [43 50]]

# Question 7

## Pandas

We have seen Numpy in the previous section. It is good at performing math operations on arrays. But the major drawback is, it cannot deal with heterogenous values. So, Pandas dataframes are helpful in that aspect for storing different data types and referring the values like a dict in python instead of just referring each item with index.

Here's how you can import pandas

In [119]:
import pandas as pd

## Series
Pandas series are almost same as arrays in numpy with a additional inferencing ability with custom labels like *keys* in a *dictionary* in python.

Here's how you can create a series

In [120]:
pd.Series(data = [1,2,3], index = ['key1', 'key2', 'key3'])

key1    1
key2    2
key3    3
dtype: int64

## Dataframes

Dataframes are the primary data structure for pandas. Two-dimensional size-mutable, potentially heterogeneous tabular data structure with labeled axes (rows and columns). Arithmetic operations align on both row and column labels. Can be thought of as a dict-like container for Series objects.

You can construct DataFrame from a dictionary

In [121]:
d = {'col1': [1, 2], 'col2': [3, 4]}
pd.DataFrame(data=d)

   col1  col2
0     1     3
1     2     4

You can construct DataFrame from a numpy array

In [0]:
pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), columns=['a', 'b', 'c'])

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

### Select specific row in given dataframe
- There is a dataframe named "df" is given below
- You have to select second row in this dataframe
- You can use "loc"
- There are multiple ways of doing it

In [140]:
df = pd.DataFrame(np.array([['a', 'b', 'c'], ['d', 'e', 'f'], ['g', 'h', 'i']]), columns=['col1', 'col2', 'col3'])
df

  col1 col2 col3
0    a    b    c
1    d    e    f
2    g    h    i

In [141]:
#extract 2nd row from the dataframe
print("2nd row in dataframe: \n", df.loc[1])

2nd row in dataframe:
 col1    d
col2    e
col3    f
Name: 1, dtype: object

### Select specific row and column value in given dataframe
- There is a dataframe named "df" is given above
- You have to select the value on first row and second column
- You have to do it using "loc" and "iloc" methods
- "loc" accepts labels for column name
- "iloc" accepts indexes

In [142]:
#select value on first row and second column using iloc

print("Value of first row second column using iloc: ", df.iloc[0,1])

Value of first row second column using iloc:  b

In [148]:
#select value on first row and second column using loc
print("value of 1st row and 2nd col using loc: ",df.loc[0]['col2'])

value of 1st row and 2nd col using loc:  b

# Question 8

## Working on dataset using dataframe

### Using the mtcars dataset.

For the below set of questions, we will be using the cars data from [Motor Trend Car Road Tests](http://stat.ethz.ch/R-manual/R-devel/library/datasets/html/mtcars.html)

The data was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973–74 models). 


Details :
    
A data frame with 32 observations on 11 (numeric) variables.

1. mpg 	Miles/(US) gallon
2. cyl 	Number of cylinders
3. disp 	Displacement (cu.in.)
4. hp 	Gross horsepower
5. drat 	Rear axle ratio
6. wt 	Weight (1000 lbs)
7. qsec 	1/4 mile time
8. vs 	Engine (0 = V-shaped, 1 = straight)
9. am 	Transmission (0 = automatic, 1 = manual)
10. gear 	Number of forward gears
11. carb 	Number of carburetors

Here's how you read a csv file in pandas
- Here we are loading mtcars dataset in a dataframe named "mtcars"

In [149]:
mtcars = pd.read_csv('mtcars.csv')

### Print first five rows of the dataframe
- Print first five rows of "mtcars" dataframe
- Use head() method

In [154]:
#using head(), extract first 5 rows from dataframe
print("First 5 rows from mtcars:")
mtcars.head(5)

First 5 rows from mtcars:

,name,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

### Print last five rows of the dataframe
- Print last five rows of "mtcars" dataframe
- Use tail() method

In [153]:
print("Last 5 rows from mtcars:")
mtcars.tail(5)

Last 5 rows from mtcars:

,name,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.9,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.5,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.5,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.6,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.6,1,1,4,2

### Display all the columns in a given dataframe
- Display all the column names of "mtcars" dataframe
- Use columns method

In [162]:
print("Display all columns in the dataframe: ", list(mtcars.columns) )


print("Another way of displaying column:\n", mtcars.columns)

Display all columns in the dataframe:  ['name', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb']
Another way of displaying column:
 Index(['name', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am',
       'gear', 'carb'],
      dtype='object')